name: Port

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
              sudo apt update
              sudo apt upgrade
              sudo apt install tree aria2 git -y
              
              # 克隆项目
              git clone https://github.com/toraidl/hyperos_port.git
              cd hyperos_port
              # 安装依赖
              sudo ./setup.sh
              #Download
              aria2c -o "1.zip" https://bn.d.miui.com/OS1.0.5.0.ULTCNXM/mayfly_images_OS1.0.5.0.ULTCNXM_20240318.0000.00_14.0_cn_a4b10bb606.tgz
              aria2c -o "2.zip" https://bn.d.miui.com/OS1.0.15.0.UNACNXM/miui_AURORA_OS1.0.15.0.UNACNXM_d2975034eb_14.0.zip
            
              # 开始移植
              sudo ./port.sh ./1.zip ./2.zip
