name: Port

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
              sudo apt update
              sudo apt install tree aria2 git -y
              
              # 克隆项目
              git clone https://github.com/toraidl/hyperos_port.git
              cd hyperos_port
              # 安装依赖
              sudo ./setup.sh
              #Download
              aria2c -o "1.zip" https://cdn.cnbj1.fds.api.mi-img.com/pangu-release-artifacts/full-ota-package/miui_HOUJIPREDPP_OS1.0.240520.1.VNCCNXM.PRE-DPP_f67f17f6e5_15.0.zip?GalaxyAccessKeyId=AKOZDLMWQMNEU5OCJW&Expires=1747972800000&?GalaxyAccessKeyId=AKOZDLMWQMNEU5OCJW&Expires=1747972800000&Signature=di60Po1O68yfc/6IdHYFUtPM7Gk=
              aria2c -o "2.zip" https://bn.d.miui.com/OS1.0.15.0.UNACNXM/miui_AURORA_OS1.0.15.0.UNACNXM_d2975034eb_14.0.zip
            
              # 开始移植
              sudo ./port.sh ./1.zip ./2.zip
