name: Port

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Remove unused packages
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: ture
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
        
    - name: Set up 
      run: |
              sudo apt update
              sudo apt install tree aria2 git
              
              # 克隆项目
              git clone https://github.com/toraidl/hyperos_port.git
              cd hyperos_port
              # 安装依赖
              sudo ./setup.sh
              #Download
              aria2c -o "1.zip" https://bn.d.miui.com/OS1.0.24.6.24.DEV/miui_MAYFLY_OS1.0.24.6.24.DEV_1061781ad5_14.0.zip
              aria2c -o "2.zip" https://bn.d.miui.com/OS1.0.24.6.29.DEV/miui_HOUJI_OS1.0.24.6.29.DEV_d0e7a173e4_14.0.zip
            
              # 开始移植
              sudo ./port.sh ./1.zip ./2.zip
